# Generated by Django 2.1.5 on 2019-01-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquilinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquilino',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
